### PR TITLE
Addition of IceNet library API usage notebook

### PR DESCRIPTION
**Pull request by bnubald**
Summary of notebook idea:

This notebook demonstrates the use of the IceNet library to programmatically generate sea-ice forecasts via the `IceNet` python interface, across all stages of a machine learning workflow, from source data download to forecast visualisation. It demonstrates this via:

* Showing usage of the IceNet library to download different climate data variables ([ERA5](https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=overview)) and sea ice concentration maps ([OSI-SAF](https://osi-saf.eumetsat.int/)) from different data sources via a similar api interface. (The ERA5 code was shown, but not run due to need for a free personal API key having been setup by the user)
* Processing of downloaded data to include normalisation and data caching to speed up the training.
* Showing the use of a high-level interface to the IceNet UNet model to train on different data sources and generate predictions of binary sea ice concentration.
* Visualising the predictions using the plotting tools within the IceNet library.

### CODE REVIEW

**Comment by bnubald** [comment]
@acocac 

Minimum working version is in this PR, please do let me know if there are any issues/comments!

[Binder](https://mybinder.org/v2/gh/bnubald/icenet-edsbook/dev_bnu)

It does use some local files (quite small) since the downloader in the example uses ftp for download which was blocked on Binder.

**Comment by acocac** [comment]
@bnubald I've seen some activity since your confirmation of the first working version, would it be ok to inspect/validate the current version? I'll have a look at it today afternoon.

**Comment by bnubald** [comment]
> @bnubald I've seen some activity since your confirmation of the first working version, would it be ok to inspect/validate the current version? I'll have a look at it today afternoon.

@acocac Sorry for the delayed response, thanks for reviewing!

Just came across a few minor issues to update, hence the activity since initial tag.

**Comment by acocac** [comment]
@bnubald thanks for implementing the changes. The notebook works for me. Can you please merge the PR into the `main` branch? Then we'll continue to the pre-review/review stages of the notebook.

Note we're skipping [Step 6](https://github.com/bnubald/icenet-edsbook?tab=readme-ov-file#point_right-step-6---transfer) in the README of the template. Instead, I'll fork the updated `main` branch to the `eds-book-gallery` organisation. Reviewers will suggest changes in the forked repository, but you can still use the original repository to implement changes suggested by reviewers. We hope this reduce additional steps for us i.e. granting new permissions for authors to the `eds-book-gallery` organisation. We'll update the README of all templates to explain this change for future contributors.

**Comment by bnubald** [comment]
@acocac Understood, thanks!

**Pull request merged**
